#!@bash
# 先提前设置root密码
# 一键式安装脚本，安装ss和v2ray插件。
# 先准备好服务端配置，直接复制进去
#设置ssh端口号22和2022，添加ssh登录的秘钥

sudo apt update
#注册net工具
sudo apt install net-tools -y

#打开谷歌云登录权限
sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sudo sed -i 's/#Port 22/Port 22/g' /etc/ssh/sshd_config
sudo echo "Port 2022" >> /etc/ssh/sshd_config
sudo service sshd restart


#Ubuntu
sudo cat /etc/localtime
#设置时区为北京时间
sudo rm -rf /etc/localtime
sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

#启动系统BBR，先写入配置 
sudo echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
sudo echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
#配置生效
sudo sysctl -p
#检验
sudo sysctl net.ipv4.tcp_available_congestion_control
sudo lsmod | grep bbr
#输出有bbr，不为空即成功


#安装ss
sudo apt install shadowsocks-libev -y
sudo apt list | grep shadowsocks-libev


#下载插件
sudo wget https://github.com/shadowsocks/v2ray-plugin/releases/download/v1.3.1/v2ray-plugin-linux-amd64-v1.3.1.tar.gz
sudo tar -zxvf v2ray-plugin-linux-amd64-v1.3.1.tar.gz
sudo mv /root/v2ray-plugin_linux_amd64 /usr/bin/v2ray-plugin
sudo ls -l /usr/bin/ | grep v2ray-plugin

sudo ls -l /etc/shadowsocks-libev/config.json
sudo rm /etc/shadowsocks-libev/config.json

sudo vi /etc/shadowsocks-libev/config.json


sudo /etc/init.d/shadowsocks-libev start

su root -c "vi /root/.ssh/authorized_keys"

sudo netstat -lpt

reboot

